export const theme = {
  typography: {
    fonts: {
      thin: "'JamGrotesque-Thin', sans-serif",
      extralight: "'JamGrotesque-ExtraLight', sans-serif",
      light: "'JamGrotesque-Light', sans-serif",
      regular: "'JamGrotesque-Regular', sans-serif",
      medium: "'JamGrotesque-Medium', sans-serif",
      semibold: "'JamGrotesque-SemiBold', sans-serif",
      bold: "'JamGrotesque-Bold', sans-serif",
      extrabold: "'JamGrotesque-ExtraBold', sans-serif",
      black: "'JamGrotesque-Black', sans-serif",
      thinItalic: "'JamGrotesque-Thin-Italic', sans-serif",
      extralightItalic: "'JamGrotesque-ExtraLight-Italic', sans-serif",
      lightItalic: "'JamGrotesque-Light-Italic', sans-serif",
      regularItalic: "'JamGrotesque-Regular-Italic', sans-serif",
      mediumItalic: "'JamGrotesque-Medium-Italic', sans-serif",
      semiboldItalic: "'JamGrotesque-SemiBold-Italic', sans-serif",
      boldItalic: "'JamGrotesque-Bold-Italic', sans-serif",
      extraboldItalic: "'JamGrotesque-ExtraBold-Italic', sans-serif",
      blackItalic: "'JamGrotesque-Black-Italic', sans-serif",
      numbers: "'RobotoFlex-VariableFont', sans-serif",
    },
    sizes: {
      header: "2em",
      body: "0.8em",
      label: "16px",
      title: "1.5em",
      helper: "0.7em",
      hint: "0.75em",
      tab: "0.6em",
      subject: "1em",
      xl: "2.5em",
    },
    weights: {
      header: 900,
      body: 500,
      title: 600,
      subject: 500,
      light: 350,
    },
    lineHeights: {
      body: "1.5",
      heading: "1.2",
    },
    letterSpacing: {
      body: "0.02em",
      heading: "0.01em",
    },
  },
  colors: {
    primary: "#f7f7f7",
    error: "#ed3500",
    accent: "#750c0c",
    textPrimary: "#f7f7f7",
    textSecondary: "#b5b5b5",
    primaryBackground: "#151515",
    secondaryBackground: "#1e2021",
    brand: {
      green: "#d6f500",
      red: "#750c0c",
      blue: "#00339f",
      white: "#f7f7f7",
    },
    disabled: "#1e2021",
    semitransparent: "#750c0c83",
  },
  spacing: {
    tight: "0.2rem",
    small: "0.5rem",
    medium: "1rem",
    large: "2rem",
    xlarge: "4rem",
  },
  borders: {
    width: {
      thin: "1px",
      medium: "2px",
      thick: "4px",
    },
    radius: {
      small: "4px",
      medium: "8px",
      big: "12px",
      large: "16px",
      rounded: "50px",
    },
    color: {
      primary: "#d6f500",
      secondary: "#1e2021",
    },
  },
  shadows: {
    small: "0 1px 3px rgba(0, 0, 0, 0.12)",
    medium: "0 4px 6px rgba(0, 0, 0, 0.16)",
    large: "0 10px 20px rgba(0, 0, 0, 0.24)",
  },
  breakpoints: {
    mobile: "480px",
    tablet: "768px",
    laptop: "1024px",
    desktop: "1200px",
  },
  zIndex: {
    subroot: -500,
    root: 0,
    suboverlay: 900,
    overlay: 1000,
    overlayContent: 1500,
    modal: 2000,
    dropdown: 500,
    tooltip: 200,
    topmost: 10000,
  },
  animations: {
    duration: {
      short: "200ms",
      medium: "400ms",
      long: "600ms",
    },
    easing: {
      easeIn: "cubic-bezier(0.5, 0, 0.5, 1)",
      easeOut: "cubic-bezier(0, 0, 0.5, 1)",
      easeInOut: "cubic-bezier(0.5, 0, 0.5, 1)",
    },
  },
  iconSizes: {
    small: "16px",
    medium: "24px",
    large: "32px",
    xlarge: "48px",
  },
};

export default theme;
